name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: 0-vortex/create-react-app-5-test/.github/workflows/compliance.yml@main
